Repository ergebnis/composer-root-version-action, pull requests merged in 2020-08, with the labels that each got.

#12 Fix: Update CHANGELOG.md
  CHANGELOG.md
Labels: bug

#13 Enhancement: Synchronize with ergebnis/php-library-template
  .editorconfig
  .github/CONTRIBUTING.md
  .github/dependabot.yml
  .github/settings.yml
  .github/workflows/deploy.yaml
  .github/workflows/integrate.yaml
  .github/workflows/prune.yaml
  .github/workflows/release.yaml
  .github/workflows/stale.yml
  .github/workflows/triage.yaml
  .gitignore
  .yamllint.yaml
  Makefile
  README.md
Labels: merge

#16 Fix: Create releases in release workflow only
  .github/workflows/deploy.yaml
Labels: bug, merge

#17 Link to official docs
  README.md
Labels: enhancement
